### ISSUE TITLE
Feedback on smart contract

### ISSUE THREAD

**Issue by KayinCheung** [fuguefoundation/smart-contracts#2]
Some thoughts from reading the code

1) In function **__callback** , let the current timestamp be stored as a variable in the smart contract. It removes the need to trust the contract owner to be honest in proving the timestamp.

2) Allow anyone to call **checkPrice** and provide a small reward for doing so. This creates an incentive for the public to call this function as soon as $1k/ETH is reached. If only the contract owner can call it, delays can happen and the winner could change in that period. Also prevents contract owner from claiming funds for himself, as he can be a participant too.

3) **Payout** function should use stored timestamp from **__callback** function to compute the winner. Function should be callable by anyone, to prevent owner from locking funds in the contract.

4) **Payout** function contains loops of unknown length. An adversary can spam guesses in the smart contract, causing an extremely long loop in **Payout** function. Worst case scenario, the gas required for the loop exceeds block gas limit and funds cannot be withdrawn.

Potential solution: A constant function can be made to display the winner. After **checkPrice** is successfully called, each participant is allowed to nominate themselves as the winner, which stores their address and time difference as a variable. If another participant nominates himself, the smart contract checks if his time difference beats the current nominated address, if yes, replace the nominated address and time difference with new values.

X number of days after **checkPrice** is called, the nominate function closes. The final nominated address should be the actual winner, unless he didn't nominate himself during this period. He is allowed to withdraw his winnings. 

In this solution, all functions run in constant time. Adversaries or contract owner cannot stop funds from being withdrawn. Technically only the winner will nominate himself as it's a waste of gas for anyone else to do so.

**Comment by fuguefoundation** [comment]
Excellent feedback, I have incorporated several of these points, including the key ingredient of having potential winners nominate themselves. Very good design principle. See new comments in README and on [Reddit](https://www.reddit.com/r/ethtrader/comments/8tgjqk/update_eth_at_1000usd_smart_contract/).
